rootfs/init: added code to mount sfs files

diff --git a/rootfs/init b/rootfs/init
--- a/rootfs/init
+++ b/rootfs/init
@@ -78,8 +78,8 @@ fi
 touch /etc/fstab
 
 # mount base and module sfs files
-[ -d "$TCOSLINK/sfs" ] ||  echo "${RED} could not find $TCOSLINK - exiting. ${NORMAL}" && exit 1
-mount -t squashfs -o loop,ro "$TCOSLINK/sfs/base.sfs" $TCOSBASE || echo "${RED} could not find $TCOSLINK/sfs/base.sfs - exiting. ${NORMAL}" && exit 1
+[ -f "$TCOSLINK/sfs/base.sfs" ] ||  echo "${RED} could not find $TCOSLINK/sfs/base.sfs - exiting. ${NORMAL}" && exit 1
+mount -t squashfs -o loop,ro "$TCOSLINK/sfs/base.sfs" $TCOSBASE || echo "${RED} could not mount $TCOSLINK/sfs/base.sfs - exiting. ${NORMAL}" && exit 1
 
 # debugshell
 
@@ -87,19 +87,16 @@ mount -t squashfs -o loop,ro "$TCOSLINK/sfs/base.sfs" $TCOSBASE || echo "${RED} 
 #########
 
 
+# other SFS
+# mount module sfs and packages sfs
+
 BRANCHES=/tcos/base
-# MOUNT MODUL SFS
 MODULE_FILES=`ls $TCOSLINK/sfs/module/*.sfs 2>/dev/null | sort` # just to have it ordered
 for i in $MODULE_FILES; do
     TARGET="$TCOSPACKAGEBASE/$(echo $(basename $i) | sed 's/\.sfs$//g')"
     mkdir -p "$TARGET"
     mount -t squashfs -o loop,ro "$i" "$TARGET"
-#    MOVEMOUNTS="$MOVEMOUNTS $TARGET"
-#    if [ "$BRANCHES" ]; then
-        BRANCHES="$TARGET $BRANCHES"
-#    else
-#        BRANCHES="$TARGET"
-#    fi
+    BRANCHES="$TARGET $BRANCHES"
 done
 
 BRANCHES=`echo $BRANCHES | sed "s/ /=rr:/g"`=rr
@@ -107,3 +104,19 @@ BRANCHES=`echo $BRANCHES | sed "s/ /=rr:/g"`=rr
 echo "------>     $BRANCHES"
 
 debugshell
+
+exit 0
+
+# mount union
+# 
+mount -t aufs -o nowarn_perm,br:/rw=rw:$BRANCHES aufs ${rootmnt}
+
+
+
+
+
+
+
+
+
+
